id: Active Directory - Get User Manager Email
version: -1
fromversion: 5.0.0
name: Active Directory - Get User Manager Email
description: Takes an email address or a username of a user account in Active Directory,
  and returns the email address of his or her manager.
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: 65b748f8-8d64-4ff1-8e55-f8050fefa13e
    type: start
    task:
      id: 65b748f8-8d64-4ff1-8e55-f8050fefa13e
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: '1'
    taskid: 1a606311-7b08-4a4b-86b8-748ee9568c6f
    type: condition
    task:
      id: 1a606311-7b08-4a4b-86b8-748ee9568c6f
      version: -1
      name: Is Active Directory enabled?
      description: Checks if the Active Directory Query v2 integration is enabled.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '13'
      'yes':
      - '2'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: brand
                      iscontext: true
                    right:
                      value:
                        simple: Active Directory Query v2
                - - operator: isEqualString
                    left:
                      value:
                        simple: state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '2':
    id: '2'
    taskid: c995aa78-63ce-4e24-803a-52b6dae5995f
    type: condition
    task:
      id: c995aa78-63ce-4e24-803a-52b6dae5995f
      version: -1
      name: By which attribute should the user be searched?
      description: Retrieves detailed information about a user account. The user can
        be specified by name, email address, or as an Active Directory Distinguished
        Name (DN). If no filter is specified, all users are returned.
      type: condition
      iscommand: false
      brand: Active Directory Query v2
    nexttasks:
      Email:
      - '5'
      Username:
      - '4'
    separatecontext: false
    conditions:
    - label: Email
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.UserEmail
                transformers:
                - operator: uniq
            iscontext: true
    - label: Username
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.Username
                transformers:
                - operator: uniq
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '4':
    id: '4'
    taskid: a4daff2e-4e2c-48f2-878c-1fe7db24ca37
    type: regular
    task:
      id: a4daff2e-4e2c-48f2-878c-1fe7db24ca37
      version: -1
      name: Get user details by username
      description: Retrieves detailed information about a user account. The user can
        be specified by name, email address, or as an Active Directory Distinguished
        Name (DN). If no filter is specified, all users are returned.
      script: Active Directory Query v2|||ad-get-user
      type: regular
      iscommand: true
      brand: Active Directory Query v2
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      attributes: {}
      custom-field-data: {}
      custom-field-type: {}
      dn: {}
      email: {}
      limit: {}
      name: {}
      user-account-control-out: {}
      username:
        complex:
          root: inputs.Username
          transformers:
          - operator: uniq
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 100,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '5':
    id: '5'
    taskid: f100ed8b-fa1e-4b6a-87ee-1d07a6e8d52f
    type: regular
    task:
      id: f100ed8b-fa1e-4b6a-87ee-1d07a6e8d52f
      version: -1
      name: Get user details by email
      description: Retrieves detailed information about a user account. The user can
        be specified by name, email address, or as an Active Directory Distinguished
        Name (DN). If no filter is specified, all users are returned.
      script: Active Directory Query v2|||ad-get-user
      type: regular
      iscommand: true
      brand: Active Directory Query v2
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      attributes: {}
      custom-field-data: {}
      custom-field-type: {}
      dn: {}
      email:
        complex:
          root: inputs.UserEmail
      limit: {}
      name: {}
      user-account-control-out: {}
      username: {}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 790,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '6':
    id: '6'
    taskid: c1b5f0d9-797a-4d66-8c40-a7a4693dcc83
    type: condition
    task:
      id: c1b5f0d9-797a-4d66-8c40-a7a4693dcc83
      version: -1
      name: Was a user manager found?
      description: Checks whether a manager name was found for the user account.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '13'
      'yes':
      - '7'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Account
                accessor: Manager
                transformers:
                - operator: uniq
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '7':
    id: '7'
    taskid: 4d5ca879-e03d-48ac-83b5-112534139e6b
    type: regular
    task:
      id: 4d5ca879-e03d-48ac-83b5-112534139e6b
      version: -1
      name: Get manager details by user email or username
      description: Retrieves detailed information about a user account. The user can
        be specified by name, email address, or as an Active Directory Distinguished
        Name (DN). If no filter is specified, all users are returned.
      script: Active Directory Query v2|||ad-get-user
      type: regular
      iscommand: true
      brand: Active Directory Query v2
    nexttasks:
      '#none#':
      - '9'
    scriptarguments:
      attributes: {}
      custom-field-data: {}
      custom-field-type: {}
      dn:
        complex:
          root: Account
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: Account.Email
                iscontext: true
              right:
                value:
                  simple: inputs.UserEmail
                iscontext: true
            - operator: isEqualString
              left:
                value:
                  simple: Account.Username
                iscontext: true
              right:
                value:
                  simple: inputs.Username
                iscontext: true
          accessor: Manager
          transformers:
          - operator: uniq
      email: {}
      limit: {}
      name: {}
      user-account-control-out: {}
      username: {}
    reputationcalc: 3
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '9':
    id: '9'
    taskid: d3edea54-041b-49c0-8528-7b504809d7fd
    type: condition
    task:
      id: d3edea54-041b-49c0-8528-7b504809d7fd
      version: -1
      name: Is there a manager email?
      description: Checks whether an email was retrieved for the manager of the user
        account.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '13'
      'yes':
      - '10'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Account
                filters:
                - - operator: isNotEqualString
                    left:
                      value:
                        simple: Account.Email
                      iscontext: true
                    right:
                      value:
                        simple: inputs.UserEmail
                      iscontext: true
                  - operator: isNotEqualString
                    left:
                      value:
                        simple: Account.Username
                      iscontext: true
                    right:
                      value:
                        simple: inputs.Username
                      iscontext: true
                accessor: Email
                transformers:
                - operator: uniq
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '10':
    id: '10'
    taskid: 36103ee0-e547-4eb0-8b1c-1b102f8a760f
    type: regular
    task:
      id: 36103ee0-e547-4eb0-8b1c-1b102f8a760f
      version: -1
      name: Set manager email to outputs
      description: Sets the email of the manager to the output context key of the
        playbook.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '12'
    scriptarguments:
      append: {}
      key:
        simple: UserManagerEmail
      value:
        complex:
          root: Account
          filters:
          - - operator: isNotEqualString
              left:
                value:
                  simple: Account.Email
                iscontext: true
              right:
                value:
                  simple: inputs.UserEmail
                iscontext: true
            - operator: isNotEqualString
              left:
                value:
                  simple: Account.Username
                iscontext: true
              right:
                value:
                  simple: inputs.Username
                iscontext: true
          accessor: Email
          transformers:
          - operator: uniq
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '12':
    id: '12'
    taskid: cd103324-58ed-4ef2-8de4-ed223a0831c0
    type: title
    task:
      id: cd103324-58ed-4ef2-8de4-ed223a0831c0
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '13':
    id: '13'
    taskid: 82beca2e-d6ae-43f2-8dbc-60d72893585c
    type: title
    task:
      id: 82beca2e-d6ae-43f2-8dbc-60d72893585c
      version: -1
      name: Cannot Retrieve Manager Email
      type: title
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '12'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1090,
          "y": 1430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "1_13_#default#": 0.22,
      "1_2_yes": 0.58,
      "2_4_Username": 0.47,
      "2_5_Email": 0.55,
      "6_13_#default#": 0.35,
      "6_7_yes": 0.47,
      "9_10_yes": 0.37,
      "9_13_#default#": 0.5
    },
    "paper": {
      "dimensions": {
        "height": 1675,
        "width": 1370,
        "x": 100,
        "y": 50
      }
    }
  }
inputs:
- key: Username
  value: {}
  required: false
  description: Search for user by the sAMAccountName attribute in Active Directory.
- key: UserEmail
  value:
    complex:
      root: Account
      accessor: Email
      transformers:
      - operator: uniq
  required: false
  description: Search for user by the email attribute in Active Directory.
outputs:
- contextPath: UserManagerEmail
  description: The email the user's manager.
tests:
  - Active Directory - Get User Manager Email - Test